### ISSUE TITLE
Discord says: "Unknown Application" on the link in README.md

### ISSUE THREAD

**Issue by Kruemmelspalter** [appellation/monstercat#25]
So the bot isn't running any more/deleted.

**Comment by Hyperfresh8080** [comment]
And you'd be probably right that it was """deleted""" when Apel got banned from Discord (but don't quote me, I THINK that's the reason. I know Apel's Pleb bot going offline was because of this ban tho)

Do feel free to fork off though and host yourself if you've got the howto...?

**Comment by appellation** [comment]
@Hyperfresh8080 is correct. The bot was deleted with my original Discord account and I haven't found it worthwhile to re-create them. However, hosting the bot shouldn't be too challenging if you're genuinely interested in running it. You might have to update some stuff and I'm not sure what the state of streaming audio from YouTube looks like, but otherwise the bot itself should still run fine.
